{{- if not .Values.jenkins.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespaceOverride }}
type: Opaque
{{- $existingSecret := lookup "v1" "Secret" .Values.namespaceOverride .Chart.Name }}
{{- $existingToken := "" }}
{{- if and $existingSecret (hasKey $existingSecret.data "JENKINS_TOKEN") }}
{{- $existingToken = (index $existingSecret.data "JENKINS_TOKEN" | b64dec) }}
{{- end }}
stringData:
   {{ .Values.jenkins.userKey | default "JENKINS_USER" }}: {{ .Values.jenkins.user | quote }}
   {{ .Values.jenkins.tokenKey | default "JENKINS_TOKEN" }}: {{- if and $existingToken (eq .Values.jenkins.token "replace-with-jenkins-api-token") }} {{ $existingToken | quote }}{{- else }} {{ .Values.jenkins.token | quote }}{{- end }}
{{- end }}
